### ISSUE TITLE
wth

### ISSUE THREAD

**Issue by killeromg007** [Ilovehiking9/Word-Bomb-Bot#1]
Traceback (most recent call last):
  File "C:\Users\James\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytesseract\pytesseract.py", line 255, in run_tesseract
    proc = subprocess.Popen(cmd_args, **subprocess_args())
  File "C:\Users\James\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\James\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\James\Desktop\Word-Bomb-Bot-main\something.py", line 58, in <module>
    text1 = OCR(mask1)
  File "C:\Users\James\Desktop\Word-Bomb-Bot-main\something.py", line 13, in OCR
    text = pytesseract.image_to_string(yest, config=custom_config)
  File "C:\Users\James\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytesseract\pytesseract.py", line 423, in image_to_string
    return {
  File "C:\Users\James\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytesseract\pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Users\James\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytesseract\pytesseract.py", line 288, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\James\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytesseract\pytesseract.py", line 260, in run_tesseract
    raise TesseractNotFoundError()
pytesseract.pytesseract.TesseractNotFoundError: C:\Program Files\Tesseract-OCR\tesseract.exe is not installed or it's not in your PATH. See README file for more information.

**Comment by killeromg007** [comment]
i install libARY
